### ISSUE TITLE
RF algorithm requires "-settings_file" instead of "-settingsfile"

### ISSUE THREAD

**Issue by AndreaLibe** [c-hydro/fp-hyde#2]
https://github.com/c-hydro/fp-hyde/blob/ca81d28fc16db75f42fa0ea8970f77709fa7131e/bin/runner/rfarm/hyde_runner_rfarm_wrf_history.sh#L69
echo " ==> COMMAND LINE: " python3 $script_file **-settings_file** $setting_file -time $time_now [time_system $time_system] 

https://github.com/c-hydro/fp-hyde/blob/ca81d28fc16db75f42fa0ea8970f77709fa7131e/bin/runner/rfarm/hyde_runner_rfarm_wrf_history.sh#L220
python3 $script_file **-settings_file** $setting_file -time $time_run

**Comment by fabiodelogu** [comment]
update code in hyde repository
