### ISSUE TITLE
"sf" is not int

### ISSUE THREAD

**Issue by AndreaLibe** [c-hydro/fp-hyde#4]
https://github.com/c-hydro/fp-hyde/blob/ca81d28fc16db75f42fa0ea8970f77709fa7131e/src/hyde/model/rfarm/lib_rfarm_apps.py#L137-L141

 xa = np.squeeze(np.nanmean(np.reshape(zi, (**int(sf)**, int(nx*ny*nt/sf)), order='F'), 0)) 
 xz = np.reshape(np.nanmean(np.reshape(xa.T, (int(nx/sf), **int(sf)**, int(ny/sf), nt), order='F'), 1), (nax,nay,nt), order='F')

**Comment by fabiodelogu** [comment]
update code in hyde repository
