### ISSUE TITLE
Problem with int()

### ISSUE THREAD

**Issue by AndreaLibe** [c-hydro/fp-hyde#6]
https://github.com/c-hydro/fp-hyde/blob/7878d2ea8747df54b959639d0625744e55fa3c36/bin/downloader/gfs/hyde_downloader_nwp_gfs.py#L306

The last line of the info_file seems to be some sort of header:

`: Date     Time   Level Gridsize    Miss :     Minimum        Mean     Maximum : Parameter ID`

The script cannot perform int(:) and it crashes. I solved it, changing L303:
https://github.com/c-hydro/fp-hyde/blob/7878d2ea8747df54b959639d0625744e55fa3c36/bin/downloader/gfs/hyde_downloader_nwp_gfs.py#L303
into
`for info_row in info_file[:-1]:`

**Comment by fabiodelogu** [comment]
update hyde repository
