### ISSUE TITLE
Incorrect slope in time estimation

### ISSUE THREAD

**Issue by AndreaLibe** [c-hydro/fp-hyde#7]
https://github.com/c-hydro/fp-hyde/blob/498cdcc2aafb5021751a0ddf36a156e0b007623d/src/hyde/model/rfarm/lib_rfarm_apps.py#L36

The slope in time should be evaluated considering the time-axis, and thus reads:
`nt_int = int(nt / 2)`
`zf[:, :, nt_int] = zf0[:, :, nt_int]/2`

**Comment by fabiodelogu** [comment]
accepted
