### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by AndreaLibe** [c-hydro/fp-hyde#8]
https://github.com/c-hydro/fp-hyde/blob/498cdcc2aafb5021751a0ddf36a156e0b007623d/bin/downloader/gsmap/hyde_downloader_satellite_gsmap.py#L544

the function `request_data_source(data_list)` is defined only in hyde_downloader_nwp_gfs.py and not imported

**Comment by fabiodelogu** [comment]
the error was complex; the mp part was bugged and now the code is fixed for all settings (sequential and multiprocessing downloading)
